{
 "title": "Haus",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "panels": [
  { "title": "Heizung", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperatur",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Außen",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "heating" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "outside" }
     ]
    },
    {
     "alias": "Vorlauf/Kessel",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "heating" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "boiler" }
     ]
    },
    {
     "alias": "Speicher",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "heating" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "reservoir" }
     ]
    },
    {
     "alias": "Rücklauf",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "heating" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "return_flow" }
     ]
    },
    {
     "alias": "Solarspeicher",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "heating" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "solar_cell" }
     ]
    },
    {
     "alias": "Solarkollektor",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "heating" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "solar_collector" }
     ]
    },
    {
     "alias": "Kessel (Soll)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "desired" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "heating" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "boiler" }
     ]
    },
    {
     "alias": "Warmwasser (Soll)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "desired" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "heating" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "warm_water" }
     ]
    },
    {
     "alias": "Auslauftemperatur",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "output" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "heating" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "warm_water" }
     ]
    }
   ]
  },
  {
   "title": "Brennerstarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "measurement": "start_count",
     "select": [
      [
       { "params": [ "current" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "heating" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "burner" }
     ]
    }
   ]
  },
  {
   "title": "Pumpe intern",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "status",
     "select": [
      [
       { "params": [ "current" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "heating" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "pump_internal" }
     ]
    }
   ]
  },
  {
   "title": "Heizungspumpe",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "status",
     "select": [
      [
       { "params": [ "current" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "heating" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "pump_heating" }
     ]
    }
   ]
  },
  {
   "title": "Laufzeit Brenner",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "alias": "Brenner",
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "current" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "heating" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "burner" }
     ]
    }
   ]
  },
  {
   "title": "Solarpumpe",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "status",
     "select": [
      [
       { "params": [ "current" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "heating" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "pump_solar_cell" }
     ]
    }
   ]
  },
  {
   "title": "Zirkulationspumpe",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "status",
     "select": [
      [
       { "params": [ "current" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "heating" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "pump_circulation" }
     ]
    }
   ]
  },
  {
   "title": "Solarleistung Heute",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "format": "watt",
   "valueName": "max",
   "targets": [
    {
     "measurement": "power",
     "query": "SELECT \"current\" FROM \"power\" WHERE (\"provider\" = 'heating' AND \"source\" = 'solar') AND $timeFilter",
     "select": [
      [
       { "params": [ "today" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "heating" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "solar" }
     ]
    }
   ]
  },
  {
   "title": "Solarleistung Gesamt",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "format": "kwatth",
   "valueName": "max",
   "targets": [
    {
     "alias": "Solarleistung Gesamt",
     "measurement": "power",
     "query": "SELECT \"current\" FROM \"power\" WHERE (\"provider\" = 'heating' AND \"source\" = 'solar') AND $timeFilter",
     "select": [
      [
       { "params": [ "all_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "heating" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "solar" }
     ]
    }
   ]
  },
  {
   "title": "Laufzeit Solar",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "alias": "Solar",
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "current" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "heating" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "solar" }
     ]
    }
   ]
  },
  { "title": "Photovoltaik", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Diesen Monat",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "watth", "label": "Leistung" }
   ],
   "targets": [
    {
     "alias": "Leistung",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT mean(\"TotW\") FROM \"PV\" WHERE $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 12" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "pv" }
     ]
    }
   ]
  },
  {
   "title": "Produziert",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 11 },
   "format": "watth",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT cumulative_sum(sum(\"avg\"))  / 12 FROM \"power\" WHERE (\"source\" = 'pv' AND \"type\" = 'production') AND $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 12" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "pv" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "production" }
     ]
    }
   ]
  },
  {
   "title": "Heute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 13, "y": 11 },
   "yaxes": [
    { "format": "watt", "label": "Leistung" }
   ],
   "targets": [
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "power",
     "query": "SELECT mean(\"TotW\") FROM \"PV\" WHERE $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "pv" }
     ]
    },
    {
     "alias": "Avg",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "power",
     "query": "SELECT mean(\"TotW\") FROM \"PV\" WHERE $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "pv" }
     ]
    },
    {
     "alias": "Min",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "power",
     "query": "SELECT mean(\"TotW\") FROM \"PV\" WHERE $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "min" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "source", "operator": "=", "value": "pv" }
     ]
    }
   ]
  },
  {
   "title": "Produziert",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "format": "watth",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT sum(\"avg\")  / 12 FROM \"power\" WHERE (\"source\" = 'pv' AND \"type\" = 'production') AND $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 12" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "pv" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "production" }
     ]
    }
   ]
  },
  {
   "title": "Umsatz",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 14 },
   "format": "currencyEUR",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT sum(\"avg\")  / 12 FROM \"power\" WHERE (\"source\" = 'pv' AND \"type\" = 'production') AND $timeFilter GROUP BY time(1d)\n",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 12 / 1000 * 0.45" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "pv" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "production" }
     ]
    }
   ]
  },
  {
   "title": "Umsatz",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 14 },
   "format": "currencyEUR",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "power",
     "query": "SELECT sum(\"avg\")  / 12 FROM \"power\" WHERE (\"source\" = 'pv' AND \"type\" = 'production') AND $timeFilter GROUP BY time(1d)\n",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 12 / 1000 * 0.45" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "pv" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "production" }
     ]
    }
   ]
  },
  {
   "title": "Peak",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 17 },
   "format": "watt",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "power",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "pv" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "production" }
     ]
    }
   ]
  },
  {
   "title": "Peak",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 17 },
   "format": "watt",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "power",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "pv" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "production" }
     ]
    }
   ]
  },
  { "title": "Internet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internet",
     "select": [
      [
       { "params": [ "upload" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internet",
     "select": [
      [
       { "params": [ "download" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Latency",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "internet",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}